import { Request, Response } from 'express';
import facebookAuthService from '../services/facebookAuthService';
import projectService from '../services/projectService';
import asyncHandler from 'express-async-handler';
import facebookDataService from '../services/facebookDataService';

export const initiateAuth = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  try {
    const { projectId } = req.query;
    const state = projectId ? String(projectId) : undefined;
    
    console.log(`[Facebook Initiate Auth] ===== BACKEND OAuth URL Generation =====`);
    console.log(`[Facebook Initiate Auth] Request received from: ${req.headers.origin || 'unknown'}`);
    console.log(`[Facebook Initiate Auth] Project ID: ${projectId}`);
    console.log(`[Facebook Initiate Auth] State: ${state}`);
    
    // Check environment variables directly
    const appIdFromEnv = process.env.FACEBOOK_APP_ID;
    const redirectUriFromEnv = process.env.FACEBOOK_REDIRECT_URI;
    
    console.log(`[Facebook Initiate Auth] FACEBOOK_APP_ID from env: ${appIdFromEnv ? `${appIdFromEnv.substring(0, 4)}...` : 'NOT SET'}`);
    console.log(`[Facebook Initiate Auth] FACEBOOK_REDIRECT_URI from env: ${redirectUriFromEnv || 'NOT SET'}`);
    
    const authUrl = facebookAuthService.generateAuthUrl(state);
    
    // Extract client_id from generated URL to verify
    const clientIdMatch = authUrl.match(/client_id=([^&]+)/);
    if (clientIdMatch) {
      const decodedClientId = decodeURIComponent(clientIdMatch[1]);
      console.log(`[Facebook Initiate Auth] ✓ Client ID in generated URL: ${decodedClientId ? `${decodedClientId.substring(0, 4)}...` : 'MISSING'}`);
      console.log(`[Facebook Initiate Auth] ✓ URL generated by BACKEND (Express/Node.js)`);
    } else {
      console.error(`[Facebook Initiate Auth] ✗ ERROR: client_id not found in generated URL!`);
    }
    
    console.log(`[Facebook Initiate Auth] Full auth URL (first 200 chars): ${authUrl.substring(0, 200)}...`);
    console.log(`[Facebook Initiate Auth] ==========================================`);
    
    res.status(200).json({
      success: true,
      data: {
        authUrl,
      },
    });
  } catch (error: any) {
    console.error(`[Facebook Initiate Auth] ERROR:`, error);
    console.error(`[Facebook Initiate Auth] Error stack:`, error.stack);
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

// GET callback handler for OAuth redirect
export const handleCallbackGet = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  console.log(`[Facebook OAuth Callback] Callback route hit!`);
  console.log(`[Facebook OAuth Callback] Query params:`, req.query);
  console.log(`[Facebook OAuth Callback] Full URL:`, req.url);
  
  const { code, state, error } = req.query;

  if (error) {
    res.redirect(`${process.env.FRONTEND_URL || 'http://localhost:5173'}/auth/facebook/callback?error=${encodeURIComponent(String(error))}`);
    return;
  }

  if (!code || !state) {
    res.redirect(`${process.env.FRONTEND_URL || 'http://localhost:5173'}/auth/facebook/callback?error=missing_code_or_state`);
    return;
  }

  const projectId = String(state);

  try {
    console.log(`[Facebook OAuth Callback] Processing callback for project: ${projectId}`);
    
    // Handle OAuth callback
    const { accessToken, refreshToken, expiresAt } = await facebookAuthService.handleCallback(String(code));
    console.log(`[Facebook OAuth Callback] Tokens received - Access token: ${accessToken ? 'Yes' : 'No'}, Refresh token: ${refreshToken ? 'Yes' : 'No'}`);

    // Save connection
    console.log(`[Facebook OAuth Callback] Saving connection to database...`);
    const savedConnection = await facebookAuthService.saveConnection(projectId, refreshToken, accessToken, expiresAt);
    console.log(`[Facebook OAuth Callback] Connection saved successfully - ID: ${savedConnection._id}, Project ID: ${savedConnection.projectId}`);

    // Verify the connection was saved
    const verifyConnection = await facebookAuthService.getConnectionByProject(projectId);
    if (!verifyConnection) {
      console.error(`[Facebook OAuth Callback] ERROR: Connection was not found after save!`);
      throw new Error('Failed to verify connection was saved');
    }
    console.log(`[Facebook OAuth Callback] Connection verified in database`);

    // Redirect to frontend callback page with success
    res.redirect(`${process.env.FRONTEND_URL || 'http://localhost:5173'}/auth/facebook/callback?facebook_connected=${projectId}`);
  } catch (error: any) {
    console.error(`[Facebook OAuth Callback] ERROR:`, error);
    console.error(`[Facebook OAuth Callback] Error stack:`, error.stack);
    res.redirect(`${process.env.FRONTEND_URL || 'http://localhost:5173'}/auth/facebook/callback?error=${encodeURIComponent(error.message)}`);
  }
});

export const saveFacebookPage = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId, pageId, pageAccessToken } = req.body;

  if (!projectId || !pageId) {
    res.status(400).json({
      success: false,
      error: 'Project ID and Page ID are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    // Verify project belongs to user
    const project = await projectService.getProjectById(projectId, userId);
    if (!project) {
      res.status(404).json({
        success: false,
        error: 'Project not found',
      });
      return;
    }

    // Get the Facebook connection to update it with page token
    const connection = await facebookAuthService.getConnectionByProject(projectId);
    if (!connection) {
      res.status(400).json({
        success: false,
        error: 'Facebook connection not found. Please reconnect.',
      });
      return;
    }

    // If no page access token provided, fetch it from the pages list
    let actualPageToken = pageAccessToken;
    if (!actualPageToken) {
      console.log(`[Facebook Save Page] No page token provided, fetching from pages list...`);
      const accessToken = await facebookDataService.getAccessToken(projectId);
      const pages = await facebookAuthService.getFacebookPages(accessToken);
      const selectedPage = pages.find(p => p.id === pageId);
      if (selectedPage?.access_token) {
        actualPageToken = selectedPage.access_token;
        console.log(`[Facebook Save Page] Found page token for page ${pageId}`);
      } else {
        console.warn(`[Facebook Save Page] Could not find page token for page ${pageId}`);
      }
    }

    // Update the Facebook connection with page access token
    if (actualPageToken) {
      connection.pageAccessToken = actualPageToken;
      connection.pageId = pageId;
      await connection.save();
      console.log(`[Facebook Save Page] Saved page access token for page ${pageId}`);
    }

    // Update project with Facebook page ID
    const updatedProject = await projectService.updateProject(projectId, userId, {
      facebookPageId: pageId,
    });

    if (!updatedProject) {
      res.status(404).json({
        success: false,
        error: 'Project not found',
      });
      return;
    }

    // Ensure facebookPageId is included in response
    const projectData = updatedProject.toObject ? updatedProject.toObject() : updatedProject;
    
    res.status(200).json({
      success: true,
      data: {
        ...projectData,
        facebookPageId: pageId, // Explicitly include to ensure it's in response
      },
    });
  } catch (error: any) {
    console.error(`[Facebook Save Page] Error:`, error);
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

export const getFacebookPages = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;

  if (!projectId) {
    res.status(400).json({
      success: false,
      error: 'Project ID is required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    // Verify project belongs to user
    const project = await projectService.getProjectById(projectId, userId);
    if (!project) {
      res.status(404).json({
        success: false,
        error: 'Project not found',
      });
      return;
    }

    // Get access token for this project
    const accessToken = await facebookDataService.getAccessToken(projectId);

    // Fetch Facebook pages
    const pages = await facebookAuthService.getFacebookPages(accessToken);

    res.status(200).json({
      success: true,
      data: pages,
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

export const getFacebookOverview = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;
  const { startDate, endDate } = req.query;

  if (!projectId) {
    res.status(400).json({
      success: false,
      error: 'Project ID is required',
    });
    return;
  }

  if (!startDate || !endDate) {
    res.status(400).json({
      success: false,
      error: 'Start date and end date are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    // Verify project belongs to user
    const project = await projectService.getProjectById(projectId, userId);
    if (!project) {
      res.status(404).json({
        success: false,
        error: 'Project not found',
      });
      return;
    }

    if (!project.facebookPageId) {
      res.status(400).json({
        success: false,
        error: 'Facebook page ID not set for this project',
      });
      return;
    }

    // Get PAGE access token (required for Page Insights API)
    const accessToken = await facebookDataService.getPageAccessToken(projectId);

    // Fetch overview metrics
    const metrics = await facebookDataService.getOverviewMetrics(
      project.facebookPageId,
      accessToken,
      {
        startDate: startDate as string,
        endDate: endDate as string,
      }
    );

    res.status(200).json({
      success: true,
      data: metrics,
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

// Get time series data for charts
export const getFacebookTimeSeries = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;
  const { startDate, endDate } = req.query;

  if (!projectId || !startDate || !endDate) {
    res.status(400).json({
      success: false,
      error: 'Project ID, start date, and end date are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    const project = await projectService.getProjectById(projectId, userId);
    if (!project || !project.facebookPageId) {
      res.status(404).json({
        success: false,
        error: 'Project or Facebook page not found',
      });
      return;
    }

    const accessToken = await facebookDataService.getPageAccessToken(projectId);
    const data = await facebookDataService.getTimeSeriesData(
      project.facebookPageId,
      accessToken,
      { startDate: startDate as string, endDate: endDate as string }
    );

    res.status(200).json({ success: true, data });
  } catch (error: any) {
    res.status(400).json({ success: false, error: error.message });
  }
});

// Get follow/unfollow data for charts
export const getFacebookFollowData = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;
  const { startDate, endDate } = req.query;

  if (!projectId || !startDate || !endDate) {
    res.status(400).json({
      success: false,
      error: 'Project ID, start date, and end date are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    const project = await projectService.getProjectById(projectId, userId);
    if (!project || !project.facebookPageId) {
      res.status(404).json({
        success: false,
        error: 'Project or Facebook page not found',
      });
      return;
    }

    const accessToken = await facebookDataService.getPageAccessToken(projectId);
    const data = await facebookDataService.getFollowData(
      project.facebookPageId,
      accessToken,
      { startDate: startDate as string, endDate: endDate as string }
    );

    res.status(200).json({ success: true, data });
  } catch (error: any) {
    res.status(400).json({ success: false, error: error.message });
  }
});

// Get posts with metrics
export const getFacebookPosts = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;
  const { startDate, endDate } = req.query;

  if (!projectId || !startDate || !endDate) {
    res.status(400).json({
      success: false,
      error: 'Project ID, start date, and end date are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    const project = await projectService.getProjectById(projectId, userId);
    if (!project || !project.facebookPageId) {
      res.status(404).json({
        success: false,
        error: 'Project or Facebook page not found',
      });
      return;
    }

    const accessToken = await facebookDataService.getPageAccessToken(projectId);
    const data = await facebookDataService.getPosts(
      project.facebookPageId,
      accessToken,
      { startDate: startDate as string, endDate: endDate as string }
    );

    res.status(200).json({ success: true, data });
  } catch (error: any) {
    res.status(400).json({ success: false, error: error.message });
  }
});

