import { Request, Response } from 'express';
import googleSearchConsoleAuthService from '../services/googleSearchConsoleAuthService';
import projectService from '../services/projectService';
import asyncHandler from 'express-async-handler';
import googleSearchConsoleDataService from '../services/googleSearchConsoleDataService';
import { googleSearchConsoleOauth2Client } from '../config/googleSearchConsole';

export const initiateAuth = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  try {
    const { projectId } = req.query;
    const state = projectId ? String(projectId) : undefined;
    
    console.log(`[Google Search Console Initiate Auth] ===== BACKEND OAuth URL Generation =====`);
    console.log(`[Google Search Console Initiate Auth] Request received from: ${req.headers.origin || 'unknown'}`);
    console.log(`[Google Search Console Initiate Auth] Project ID: ${projectId}`);
    console.log(`[Google Search Console Initiate Auth] State: ${state}`);
    
    // Verify redirect URI configuration
    const redirectUri = process.env.GOOGLE_SEARCH_CONSOLE_REDIRECT_URL || 'http://localhost:3000/api/gsc/callback';
    console.log(`[Google Search Console Initiate Auth] Redirect URI from env: ${redirectUri}`);
    
    // Generate auth URL from backend (this is the ONLY place URL should be generated)
    const authUrl = googleSearchConsoleAuthService.generateAuthUrl(state);
    
    // Extract redirect_uri from generated URL to verify
    const redirectUriMatch = authUrl.match(/redirect_uri=([^&]+)/);
    if (redirectUriMatch) {
      const decodedRedirectUri = decodeURIComponent(redirectUriMatch[1]);
      console.log(`[Google Search Console Initiate Auth] ✓ Redirect URI in generated URL: ${decodedRedirectUri}`);
      console.log(`[Google Search Console Initiate Auth] ✓ URL generated by BACKEND (Express/Node.js)`);
    } else {
      console.error(`[Google Search Console Initiate Auth] ✗ ERROR: redirect_uri not found in generated URL!`);
    }
    
    console.log(`[Google Search Console Initiate Auth] Full auth URL (first 200 chars): ${authUrl.substring(0, 200)}...`);
    console.log(`[Google Search Console Initiate Auth] ==========================================`);
    
    res.status(200).json({
      success: true,
      data: {
        authUrl,
      },
    });
  } catch (error: any) {
    console.error(`[Google Search Console Initiate Auth] ERROR:`, error);
    console.error(`[Google Search Console Initiate Auth] Error stack:`, error.stack);
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

// GET callback handler for OAuth redirect
export const handleCallbackGet = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  console.log(`[Google Search Console OAuth Callback] Callback route hit!`);
  console.log(`[Google Search Console OAuth Callback] Query params:`, req.query);
  console.log(`[Google Search Console OAuth Callback] Full URL:`, req.url);
  console.log(`[Google Search Console OAuth Callback] Expected redirect URI: ${process.env.GOOGLE_SEARCH_CONSOLE_REDIRECT_URL || 'http://localhost:3000/api/gsc/callback'}`);
  
  const { code, state, error } = req.query;

  if (error) {
    res.redirect(`${process.env.FRONTEND_URL || 'http://localhost:5173'}/auth/google-search-console/callback?error=${encodeURIComponent(String(error))}`);
    return;
  }

  if (!code || !state) {
    res.redirect(`${process.env.FRONTEND_URL || 'http://localhost:5173'}/auth/google-search-console/callback?error=missing_code_or_state`);
    return;
  }

  const projectId = String(state);

  try {
    console.log(`[Google Search Console OAuth Callback] Processing callback for project: ${projectId}`);
    
    // Handle OAuth callback
    const { accessToken, refreshToken, expiresAt } = await googleSearchConsoleAuthService.handleCallback(String(code));
    console.log(`[Google Search Console OAuth Callback] Tokens received - Access token: ${accessToken ? 'Yes' : 'No'}, Refresh token: ${refreshToken ? 'Yes' : 'No'}`);

    // Save connection
    console.log(`[Google Search Console OAuth Callback] Saving connection to database...`);
    const savedConnection = await googleSearchConsoleAuthService.saveConnection(projectId, refreshToken, accessToken, expiresAt);
    console.log(`[Google Search Console OAuth Callback] Connection saved successfully - ID: ${savedConnection._id}, Project ID: ${savedConnection.projectId}`);

    // Verify the connection was saved
    const verifyConnection = await googleSearchConsoleAuthService.getConnectionByProject(projectId);
    if (!verifyConnection) {
      console.error(`[Google Search Console OAuth Callback] ERROR: Connection was not found after save!`);
      throw new Error('Failed to verify connection was saved');
    }
    console.log(`[Google Search Console OAuth Callback] Connection verified in database`);

    // Redirect to frontend callback page with success
    res.redirect(`${process.env.FRONTEND_URL || 'http://localhost:5173'}/auth/google-search-console/callback?search_console_connected=${projectId}`);
  } catch (error: any) {
    console.error(`[Google Search Console OAuth Callback] ERROR:`, error);
    console.error(`[Google Search Console OAuth Callback] Error stack:`, error.stack);
    res.redirect(`${process.env.FRONTEND_URL || 'http://localhost:5173'}/auth/google-search-console/callback?error=${encodeURIComponent(error.message)}`);
  }
});

// POST callback handler for manual callback
export const handleCallback = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { code, projectId } = req.body;

  if (!code || !projectId) {
    res.status(400).json({
      success: false,
      error: 'Authorization code and project ID are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    // Verify project belongs to user
    const project = await projectService.getProjectById(projectId, userId);
    if (!project) {
      res.status(404).json({
        success: false,
        error: 'Project not found',
      });
      return;
    }

    // Handle OAuth callback
    const { accessToken, refreshToken, expiresAt } = await googleSearchConsoleAuthService.handleCallback(code);

    // Save connection
    await googleSearchConsoleAuthService.saveConnection(projectId, refreshToken, accessToken, expiresAt);

    res.status(200).json({
      success: true,
      data: {
        message: 'Google Search Console connection established successfully',
      },
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

export const saveSearchConsoleSite = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId, siteUrl } = req.body;

  if (!projectId || !siteUrl) {
    res.status(400).json({
      success: false,
      error: 'Project ID and Site URL are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    // Verify project belongs to user
    const project = await projectService.getProjectById(projectId, userId);
    if (!project) {
      res.status(404).json({
        success: false,
        error: 'Project not found',
      });
      return;
    }

    // Update project with Search Console site URL
    const updatedProject = await projectService.updateProject(projectId, userId, {
      searchConsoleSiteUrl: siteUrl,
    });

    if (!updatedProject) {
      res.status(404).json({
        success: false,
        error: 'Project not found',
      });
      return;
    }

    const projectData = updatedProject.toObject ? updatedProject.toObject() : updatedProject;
    
    res.status(200).json({
      success: true,
      data: {
        ...projectData,
        searchConsoleSiteUrl: siteUrl,
      },
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

export const getSearchConsoleSites = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;

  if (!projectId) {
    res.status(400).json({
      success: false,
      error: 'Project ID is required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    const project = await projectService.getProjectById(projectId, userId);
    if (!project) {
      res.status(404).json({
        success: false,
        error: 'Project not found',
      });
      return;
    }

    // Get access token for this project
    const accessToken = await googleSearchConsoleDataService.getAccessToken(projectId);

    // Fetch Search Console sites
    const sites = await googleSearchConsoleAuthService.getSearchConsoleSites(accessToken);

    res.status(200).json({
      success: true,
      data: sites,
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

export const getSearchConsoleOverview = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;
  const { startDate, endDate } = req.query;

  if (!projectId) {
    res.status(400).json({
      success: false,
      error: 'Project ID is required',
    });
    return;
  }

  if (!startDate || !endDate) {
    res.status(400).json({
      success: false,
      error: 'Start date and end date are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    const project = await projectService.getProjectById(projectId, userId);
    if (!project) {
      res.status(404).json({
        success: false,
        error: 'Project not found',
      });
      return;
    }

    if (!project.searchConsoleSiteUrl) {
      res.status(400).json({
        success: false,
        error: 'Search Console site URL not set for this project',
      });
      return;
    }

    const accessToken = await googleSearchConsoleDataService.getAccessToken(projectId);

    const overview = await googleSearchConsoleDataService.getSearchAnalytics(
      project.searchConsoleSiteUrl,
      accessToken,
      {
        startDate: startDate as string,
        endDate: endDate as string,
      }
    );

    res.status(200).json({
      success: true,
      data: overview,
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

export const getSearchConsoleQueries = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;
  const { startDate, endDate } = req.query;

  if (!projectId || !startDate || !endDate) {
    res.status(400).json({
      success: false,
      error: 'Project ID, start date and end date are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    const project = await projectService.getProjectById(projectId, userId);
    if (!project || !project.searchConsoleSiteUrl) {
      res.status(404).json({
        success: false,
        error: 'Project or Search Console site URL not found',
      });
      return;
    }

    const accessToken = await googleSearchConsoleDataService.getAccessToken(projectId);

    const queries = await googleSearchConsoleDataService.getTopQueries(
      project.searchConsoleSiteUrl,
      accessToken,
      {
        startDate: startDate as string,
        endDate: endDate as string,
      }
    );

    res.status(200).json({
      success: true,
      data: queries,
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

export const getSearchConsolePages = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;
  const { startDate, endDate } = req.query;

  if (!projectId || !startDate || !endDate) {
    res.status(400).json({
      success: false,
      error: 'Project ID, start date and end date are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    const project = await projectService.getProjectById(projectId, userId);
    if (!project || !project.searchConsoleSiteUrl) {
      res.status(404).json({
        success: false,
        error: 'Project or Search Console site URL not found',
      });
      return;
    }

    const accessToken = await googleSearchConsoleDataService.getAccessToken(projectId);

    const pages = await googleSearchConsoleDataService.getTopPages(
      project.searchConsoleSiteUrl,
      accessToken,
      {
        startDate: startDate as string,
        endDate: endDate as string,
      }
    );

    res.status(200).json({
      success: true,
      data: pages,
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

export const getSearchConsoleCountries = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;
  const { startDate, endDate } = req.query;

  if (!projectId || !startDate || !endDate) {
    res.status(400).json({
      success: false,
      error: 'Project ID, start date and end date are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    const project = await projectService.getProjectById(projectId, userId);
    if (!project || !project.searchConsoleSiteUrl) {
      res.status(404).json({
        success: false,
        error: 'Project or Search Console site URL not found',
      });
      return;
    }

    const accessToken = await googleSearchConsoleDataService.getAccessToken(projectId);

    const countries = await googleSearchConsoleDataService.getCountries(
      project.searchConsoleSiteUrl,
      accessToken,
      {
        startDate: startDate as string,
        endDate: endDate as string,
      }
    );

    res.status(200).json({
      success: true,
      data: countries,
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

export const getSearchConsoleDevices = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;
  const { startDate, endDate } = req.query;

  if (!projectId || !startDate || !endDate) {
    res.status(400).json({
      success: false,
      error: 'Project ID, start date and end date are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    const project = await projectService.getProjectById(projectId, userId);
    if (!project || !project.searchConsoleSiteUrl) {
      res.status(404).json({
        success: false,
        error: 'Project or Search Console site URL not found',
      });
      return;
    }

    const accessToken = await googleSearchConsoleDataService.getAccessToken(projectId);

    const devices = await googleSearchConsoleDataService.getDevices(
      project.searchConsoleSiteUrl,
      accessToken,
      {
        startDate: startDate as string,
        endDate: endDate as string,
      }
    );

    res.status(200).json({
      success: true,
      data: devices,
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

