import { Request, Response } from 'express';
import metaAdsAuthService from '../services/metaAdsAuthService';
import projectService from '../services/projectService';
import asyncHandler from 'express-async-handler';
import metaAdsDataService from '../services/metaAdsDataService';

// Route 1: Get auth URL
export const getAuthUrl = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  try {
    const { projectId } = req.query;
    const state = projectId ? String(projectId) : undefined;
    
    console.log(`[Meta Ads Get Auth URL] ===== BACKEND OAuth URL Generation =====`);
    console.log(`[Meta Ads Get Auth URL] Request received from: ${req.headers.origin || 'unknown'}`);
    console.log(`[Meta Ads Get Auth URL] Project ID: ${projectId}`);
    console.log(`[Meta Ads Get Auth URL] State: ${state}`);
    
    // Check environment variables directly
    const appIdFromEnv = process.env.FACEBOOK_APP_ID;
    const redirectUriFromEnv = process.env.META_ADS_REDIRECT_URI;
    
    console.log(`[Meta Ads Get Auth URL] FACEBOOK_APP_ID from env: ${appIdFromEnv ? `${appIdFromEnv.substring(0, 4)}...` : 'NOT SET'}`);
    console.log(`[Meta Ads Get Auth URL] META_ADS_REDIRECT_URI from env: ${redirectUriFromEnv || 'NOT SET'}`);
    
    const authUrl = metaAdsAuthService.generateAuthUrl(state);
    
    // Extract client_id from generated URL to verify
    const clientIdMatch = authUrl.match(/client_id=([^&]+)/);
    if (clientIdMatch) {
      const decodedClientId = decodeURIComponent(clientIdMatch[1]);
      console.log(`[Meta Ads Get Auth URL] ✓ Client ID in generated URL: ${decodedClientId ? `${decodedClientId.substring(0, 4)}...` : 'MISSING'}`);
      console.log(`[Meta Ads Get Auth URL] ✓ URL generated by BACKEND (Express/Node.js)`);
    } else {
      console.error(`[Meta Ads Get Auth URL] ✗ ERROR: client_id not found in generated URL!`);
    }
    
    console.log(`[Meta Ads Get Auth URL] Full auth URL (first 200 chars): ${authUrl.substring(0, 200)}...`);
    console.log(`[Meta Ads Get Auth URL] ==========================================`);
    
    res.status(200).json({
      success: true,
      data: {
        authUrl,
      },
    });
  } catch (error: any) {
    console.error(`[Meta Ads Get Auth URL] ERROR:`, error);
    console.error(`[Meta Ads Get Auth URL] Error stack:`, error.stack);
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

// Route 2: Handle OAuth callback
export const handleCallback = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  console.log(`[Meta Ads OAuth Callback] Callback route hit!`);
  console.log(`[Meta Ads OAuth Callback] Query params:`, req.query);
  console.log(`[Meta Ads OAuth Callback] Full URL:`, req.url);
  
  const { code, state, error } = req.query;

  if (error) {
    res.redirect(`${process.env.FRONTEND_URL || 'http://localhost:5173'}/auth/meta-ads/callback?error=${encodeURIComponent(String(error))}`);
    return;
  }

  if (!code || !state) {
    res.redirect(`${process.env.FRONTEND_URL || 'http://localhost:5173'}/auth/meta-ads/callback?error=missing_code_or_state`);
    return;
  }

  const projectId = String(state);

  try {
    console.log(`[Meta Ads OAuth Callback] Processing callback for project: ${projectId}`);
    
    // Handle OAuth callback
    const { accessToken, refreshToken, expiresAt } = await metaAdsAuthService.handleCallback(String(code));
    console.log(`[Meta Ads OAuth Callback] Tokens received - Access token: ${accessToken ? 'Yes' : 'No'}, Refresh token: ${refreshToken ? 'Yes' : 'No'}`);

    // Save connection
    console.log(`[Meta Ads OAuth Callback] Saving connection to database...`);
    const savedConnection = await metaAdsAuthService.saveConnection(projectId, refreshToken, accessToken, expiresAt);
    console.log(`[Meta Ads OAuth Callback] Connection saved successfully - ID: ${savedConnection._id}, Project ID: ${savedConnection.projectId}`);

    // Verify the connection was saved
    const verifyConnection = await metaAdsAuthService.getConnectionByProject(projectId);
    if (!verifyConnection) {
      console.error(`[Meta Ads OAuth Callback] ERROR: Connection was not found after save!`);
      throw new Error('Failed to verify connection was saved');
    }
    console.log(`[Meta Ads OAuth Callback] Connection verified in database`);

    // Redirect to frontend callback page with success
    res.redirect(`${process.env.FRONTEND_URL || 'http://localhost:5173'}/auth/meta-ads/callback?meta_ads_connected=${projectId}`);
  } catch (error: any) {
    console.error(`[Meta Ads OAuth Callback] ERROR:`, error);
    console.error(`[Meta Ads OAuth Callback] Error stack:`, error.stack);
    res.redirect(`${process.env.FRONTEND_URL || 'http://localhost:5173'}/auth/meta-ads/callback?error=${encodeURIComponent(error.message)}`);
  }
});

// Route 3: Get ad accounts for selection
export const getAdAccounts = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;

  if (!projectId) {
    res.status(400).json({
      success: false,
      error: 'Project ID is required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    // Verify project belongs to user
    const project = await projectService.getProjectById(projectId, userId);
    if (!project) {
      res.status(404).json({
        success: false,
        error: 'Project not found',
      });
      return;
    }

    // Get access token for this project
    const accessToken = await metaAdsDataService.getAccessToken(projectId);

    // Fetch Meta Ads accounts
    const accounts = await metaAdsAuthService.getAdAccounts(accessToken);

    res.status(200).json({
      success: true,
      data: accounts,
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

// Route 4: Save selected ad account
export const saveAdAccount = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId, accountId } = req.body;

  if (!projectId || !accountId) {
    res.status(400).json({
      success: false,
      error: 'Project ID and Account ID are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    // Verify project belongs to user
    const project = await projectService.getProjectById(projectId, userId);
    if (!project) {
      res.status(404).json({
        success: false,
        error: 'Project not found',
      });
      return;
    }

    // Update project with Meta Ads account ID
    const updatedProject = await projectService.updateProject(projectId, userId, {
      metaAdsAccountId: accountId,
    });

    if (!updatedProject) {
      res.status(404).json({
        success: false,
        error: 'Project not found',
      });
      return;
    }

    // Ensure metaAdsAccountId is included in response
    const projectData = updatedProject.toObject ? updatedProject.toObject() : updatedProject;
    
    res.status(200).json({
      success: true,
      data: {
        ...projectData,
        metaAdsAccountId: accountId, // Explicitly include to ensure it's in response
      },
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

// Route 5: Get insights
export const getInsights = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;
  const { startDate, endDate } = req.query;

  if (!projectId) {
    res.status(400).json({
      success: false,
      error: 'Project ID is required',
    });
    return;
  }

  if (!startDate || !endDate) {
    res.status(400).json({
      success: false,
      error: 'Start date and end date are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    // Verify project belongs to user
    const project = await projectService.getProjectById(projectId, userId);
    if (!project) {
      res.status(404).json({
        success: false,
        error: 'Project not found',
      });
      return;
    }

    if (!project.metaAdsAccountId) {
      res.status(400).json({
        success: false,
        error: 'Meta Ads account ID not set for this project',
      });
      return;
    }

    // Get access token
    const accessToken = await metaAdsDataService.getAccessToken(projectId);

    // Fetch insights
    const insights = await metaAdsDataService.getInsights(
      project.metaAdsAccountId,
      accessToken,
      {
        startDate: startDate as string,
        endDate: endDate as string,
      }
    );

    res.status(200).json({
      success: true,
      data: insights,
    });
  } catch (error: any) {
    res.status(400).json({
      success: false,
      error: error.message,
    });
  }
});

// Route 6: Get campaigns
export const getCampaigns = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;
  const { startDate, endDate } = req.query;

  if (!projectId || !startDate || !endDate) {
    res.status(400).json({
      success: false,
      error: 'Project ID, start date, and end date are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    const project = await projectService.getProjectById(projectId, userId);
    if (!project || !project.metaAdsAccountId) {
      res.status(404).json({
        success: false,
        error: 'Project or Meta Ads account not found',
      });
      return;
    }

    const accessToken = await metaAdsDataService.getAccessToken(projectId);
    const campaigns = await metaAdsDataService.getCampaigns(
      project.metaAdsAccountId,
      accessToken,
      { startDate: startDate as string, endDate: endDate as string }
    );

    res.status(200).json({ success: true, data: campaigns });
  } catch (error: any) {
    res.status(400).json({ success: false, error: error.message });
  }
});

// Route 7: Get age/gender breakdown
export const getAgeGenderBreakdown = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;
  const { startDate, endDate } = req.query;

  if (!projectId || !startDate || !endDate) {
    res.status(400).json({
      success: false,
      error: 'Project ID, start date, and end date are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    const project = await projectService.getProjectById(projectId, userId);
    if (!project || !project.metaAdsAccountId) {
      res.status(404).json({
        success: false,
        error: 'Project or Meta Ads account not found',
      });
      return;
    }

    const accessToken = await metaAdsDataService.getAccessToken(projectId);
    const breakdown = await metaAdsDataService.getAgeGenderBreakdown(
      project.metaAdsAccountId,
      accessToken,
      { startDate: startDate as string, endDate: endDate as string }
    );

    res.status(200).json({ success: true, data: breakdown });
  } catch (error: any) {
    res.status(400).json({ success: false, error: error.message });
  }
});

// Route 8: Get platform breakdown
export const getPlatformBreakdown = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;
  const { startDate, endDate } = req.query;

  if (!projectId || !startDate || !endDate) {
    res.status(400).json({
      success: false,
      error: 'Project ID, start date, and end date are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    const project = await projectService.getProjectById(projectId, userId);
    if (!project || !project.metaAdsAccountId) {
      res.status(404).json({
        success: false,
        error: 'Project or Meta Ads account not found',
      });
      return;
    }

    const accessToken = await metaAdsDataService.getAccessToken(projectId);
    const breakdown = await metaAdsDataService.getPlatformBreakdown(
      project.metaAdsAccountId,
      accessToken,
      { startDate: startDate as string, endDate: endDate as string }
    );

    res.status(200).json({ success: true, data: breakdown });
  } catch (error: any) {
    res.status(400).json({ success: false, error: error.message });
  }
});

// Route 9: Get daily breakdown for charts
export const getDailyBreakdown = asyncHandler(async (req: Request, res: Response): Promise<void> => {
  const { projectId } = req.params;
  const { startDate, endDate } = req.query;

  if (!projectId || !startDate || !endDate) {
    res.status(400).json({
      success: false,
      error: 'Project ID, start date, and end date are required',
    });
    return;
  }

  try {
    // @ts-ignore
    const userId = req.user._id.toString();
    
    const project = await projectService.getProjectById(projectId, userId);
    if (!project || !project.metaAdsAccountId) {
      res.status(404).json({
        success: false,
        error: 'Project or Meta Ads account not found',
      });
      return;
    }

    const accessToken = await metaAdsDataService.getAccessToken(projectId);
    const dailyData = await metaAdsDataService.getDailyBreakdown(
      project.metaAdsAccountId,
      accessToken,
      { startDate: startDate as string, endDate: endDate as string }
    );

    res.status(200).json({ success: true, data: dailyData });
  } catch (error: any) {
    res.status(400).json({ success: false, error: error.message });
  }
});

